config/routes.rb
Recommend::Application.routes.draw do
  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :skip => [:sessions, :registrations]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    get 'signup' => 'registrations#new', :as => :new_user_registration
    post 'signup' => 'registrations#create', :as => :user_registration
    get 'signup/cancel' => 'registrations#cancel', :as => :cancel_user_registration
    get 'account/edit' => 'registrations#edit', :as => :edit_user_registration
    put 'account' => 'registrations#update'
    delete 'account' => 'registrations#destroy'
    match 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via
  end
  resources :users, :except => [:edit] do
    resources :recommendations do
      member do
        get "feedback"
        post "submit_feedback"
      end
    end
    member do
      get "profile"
      get "events"
      get "edit_profile"
      put "update_profile"
      get "tweet"
      post "post_tweet"
    end
  end

  root :to => redirect("/signin")

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications, :dependent => :destroy
  has_many :social_accounts, :dependent => :destroy
  has_one :profile, :dependent => :destroy
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :profession, :first_name, :last_name
  attr_accessible :social_accounts_attributes
  attr_accessor :social_account_name, :social_account_type

  accepts_nested_attributes_for :social_accounts, :allow_destroy => true
  
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :username, :presence => true
  validates :username, :uniqueness => true
  
  after_create :create_profile

  def apply_omniauth(omniauth)
    #puts omniauth.inspect
    if omniauth['info']
      self.email = omniauth['info']['email']
      self.first_name = omniauth['info']['first_name'] || (omniauth['info']['name'].split(" ", 2).first rescue "")
      self.last_name = omniauth['info']['last_name'] || (omniauth['info']['name'].split(" ", 2).last  rescue "")
    end
    authentications.build(:provider => filter_provider(omniauth['provider']), :uid => omniauth['uid'], :token => omniauth['credentials']['token'], :secret => omniauth['credentials']['secret'], :account_name => filter_account_name(omniauth))
    social_accounts.build(:account_type => SocialAccount::ACCOUNT_TYPES[filter_provider(omniauth['provider']).to_sym], :account_name => filter_account_name(omniauth))
    self.confirmed_at = DateTime.now
  end

  def name
    "#{first_name} #{last_name}"
  end
  
  def password_required?
    (authentications.empty? || !password.blank?) && super
  end

  def post_tweet(message)
    Twitter.configure do |config|
      config.consumer_key = OMNIAUTH_CONFIG["twitter"]["key"]
      config.consumer_secret = OMNIAUTH_CONFIG["twitter"]["secret"]
      config.oauth_token = twitter_account.token
      config.oauth_token_secret = twitter_account.secret
    end
    client = Twitter::Client.new
    begin
      client.update(message)
      return true
    rescue Exception => e
      self.errors.add(:oauth_token, "Unable to send to twitter: #{e.to_s}")
      return false
    end
  end

  def facebook_account
    if @facebook_account.nil?
      @facebook_account = authentications.find_by_provider("facebook")
    end
    @facebook_account
  end

  def twitter_account
    if @twitter_account.nil?
      @twitter_account = authentications.find_by_provider("twitter")
    end
    @twitter_account
  end

  def has_facebook?
    if @facebook_account.nil?
      @facebook_account = authentications.find_by_provider("facebook")
    end
    @facebook_account.present?
  end

  def has_twitter?
    if @twitter_account.nil?
      @twitter_account = authentications.find_by_provider("twitter")
    end
    @twitter_account.present?
  end

  private
  def create_profile
    profile = self.build_profile({:display_name => name })
    profile.save(:validate => false)
  end

  def filter_provider(provider)
    if provider == 'google_oauth2'
      "google"
    else
      provider
    end
  end

  def filter_account_name(omniauth)
    if omniauth['provider'] == 'google_oauth2'
      omniauth['uid']
    else
      omniauth['info']['nickname']
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :only => [:edit_profile, :update_profile]
  before_filter :load_user
  before_filter :can_access, :only => [:edit_profile, :update_profile]
  before_filter :can_access_by_user, :only => [:edit_profile, :update_profile]
  # GET /users/1
  # GET /users/1.json
  def show
    #    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def update_profile
    #    @user = User.find_by_id(params[:id])
    @profile = @user.profile
    if @profile.update_attributes(params[:profile])
      redirect_to profile_user_path(@user)
      return
    else
      render action: "edit_profile"
    end
  end

  def profile
    #    @user = User.find(params[:id])
    @profile = @user.profile
    
  end

  def events
    @fbuser = FbGraph::User.fetch(@user.authentications.first.account_name, :access_token => @user.authentications.first.token)
    @events = @fbuser.events
  end
  
  def edit_profile
    #    @user = User.find(params[:id])
    @profile = @user.profile
  end

  def tweet
  end

  def post_tweet
    @user.post_tweet(params[:tweet])
    redirect_to profile_user_path(@user), :notice => "Your tweet has been posted"
  end

  private
  def load_user
    @user = User.find(params[:id])
  end
  
  def can_access
    @can_access = @user.id == current_user.id 
  end

  def can_access_by_user
    redirect_to profile_user_path(current_user) unless @can_access
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def get_social_icon(account_type, account_name)
    if(account_type == SocialAccount::TYPE_LINKEDIN)
      return link_to(image_tag("linkedin.png", :class => "menu_icon"), "http://www.linkedin.com/#{account_name}", :target => '_blank')
    elsif(account_type == SocialAccount::TYPE_TWITTER)
      return link_to(image_tag("twitter.png", :class => "menu_icon"), "http://www.twitter.com/#{account_name}", :target => '_blank')
    elsif(account_type == SocialAccount::TYPE_FACEBOOK)
      return link_to(image_tag("facebook.png", :class => "menu_icon"), "http://www.facebook.com/#{account_name}", :target => '_blank')
    elsif(account_type == SocialAccount::TYPE_FOURSQUARE)
      return link_to(image_tag("foursquare.png", :class => "menu_icon"), "https://foursquare.com/#{account_name}", :target => '_blank')
    elsif(account_type == SocialAccount::TYPE_GOOGLE)
      return link_to(image_tag("google_32.png", :class => "menu_icon"), "https://plus.google.com/#{account_name}", :target => '_blank')
    end
  end
  
end

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :username, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :username, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :profession, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :profession, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/_form_error.html.erb
<% @model.errors.full_messages.each do |msg| %>
  <p><%= msg %></p>
<% end %>

app/views/users/_social_account_fields.html.erb
<div class="fields">
  <table>
    <tr>
      <td>
        <%= f.label :account_name, "User Name" %>
        <%= f.text_field :account_name %>
      </td>
      <td style="width: 10px"></td>
      <td>
        <%= f.label :account_type, "Type" %>
        <%= f.select :account_type, SocialAccount::ACCOUNT_TYPES.collect {|key, value| [key.to_s.capitalize, value] }, {:include_blank => "-- Select Social Account --"}, {:disabled => !f.object.new_record?} %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.hidden_field :_destroy %>
        <%= link_to_function "remove", "remove_fields(this)", :id => "remove_fields" %>
        <p class="notice">
        </p>
      </td>
    </tr>
  </table>
</div>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/edit_profile.html.erb
<h2>Edit Profile</h2>
<div>
</div>

<%= form_for(@profile, :url => update_profile_user_path(@user), :html => { :multipart => true }) do |f| %>
  <div>
    <%= render :partial => "form_error", :locals => {:@model => @profile} %>
  </div>
  <div>
    <%= f.label :display_name %><br />
    <%= f.text_field :display_name %>
  </div><br/>
  <div>
    <%= f.label :about_me %><br />
    <%= f.text_field :about_me %>
  </div><br/>
  <%= f.fields_for :user do |ff| %>
  <p>
      <%= ff.label :profession, "Profession" %><br />
      <%= ff.text_field :profession %><br />
    </p>
    <p>
      <%= ff.label :email, "Email" %><br />
      <%= ff.text_field :email %><br />
    </p>
    
    <%= ff.fields_for :social_accounts do |social_accounts| %>
     <%= render 'social_account_fields', :f => social_accounts %>
    <% end %>
 <p><%= link_to_add_fields "Add Social Account", ff, :social_accounts %></p>
  <% end %>

  <div>
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>
  <div style="height: 8px"></div>
  <div>
    <%= link_to t('.back', :default => t("helpers.links.back")),
      profile_user_path(@user), :class => 'btn'  %>
    <%= f.submit "Update",:class => 'btn' %>
  </div>

<% end %>

app/views/users/events.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => "Facebook Events" %></h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Start time</th>
      <th>Location</th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.start_time %></td>
        <td><%= event.location %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:username) %></th>
      <th><%= model_class.human_attribute_name(:profession) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.username %></td>
        <td><%= user.profession %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%#= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/profile.html.erb
<p>
<h4><%=@profile.display_name%>'s  Profile</h4>
</p>
<%if (@profile != nil)%>
  <p>
    Name : <%=@profile.display_name%>
  </p>
  <% if user_signed_in? %>
    <p>
      Email : <%=@profile.user.email%>
    </p>
  <%end%>
  <p>
    About Me : <%=@profile.about_me%>
  </p>
  <p>
    Profile Picture : <%= image_tag @profile.photo.url(:small) %>
  </p>
<%end%>
  

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>
<div>
<%=link_to  "View Profile",profile_user_path(@user)%>
</div>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @user.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @user.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:username) %>:</strong></dt>
  <dd><%= @user.username %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
    users_path, :class => 'btn'  %>
  <%#= link_to t('.edit', :default => t("helpers.links.edit")),
    edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
    user_path(@user),
    :method => 'delete',
    :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
    :class => 'btn btn-danger' %>
</div>

app/views/users/tweet.html.erb
<%= form_tag(post_tweet_user_path(@user), :method => :post) do  %>
  <%= text_area_tag "tweet", nil, :placeholder => "tweet", :value => params[:tweet] %>
  <%= submit_tag "Tweet" %>
<%- end %>