config/routes.rb
Recommend::Application.routes.draw do
  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :skip => [:sessions, :registrations]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    get 'signup' => 'registrations#new', :as => :new_user_registration
    post 'signup' => 'registrations#create', :as => :user_registration
    get 'signup/cancel' => 'registrations#cancel', :as => :cancel_user_registration
    get 'account/edit' => 'registrations#edit', :as => :edit_user_registration
    put 'account' => 'registrations#update'
    delete 'account' => 'registrations#destroy'
    match 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via
  end
  resources :users, :except => [:edit] do
    resources :recommendations do
      member do
        get "feedback"
        post "submit_feedback"
      end
    end
    member do
      get "profile"
      get "events"
      get "edit_profile"
      put "update_profile"
      get "tweet"
      post "post_tweet"
    end
  end

  root :to => redirect("/signin")

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Demo" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->


    <%= stylesheet_link_tag "application", :media => "all" %>
    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%# favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Rails Demo</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav pull-right">
              <% if user_signed_in? %>
                <li><%= link_to("Signed in as #{current_user.email}", profile_user_path(current_user)) %></li>
                <li class="divider-vertical"></li>
              <% end %>

              <% if user_signed_in? %>
                <li><%= link_to("Log Out", destroy_user_session_path, :method => :delete) %></li>
              <% else %>
                <li><%= link_to "Sign In",user_session_path() %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
	 <% if current_user %>
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Profile", user_signed_in? ? profile_user_path(current_user) : "#"  %></li>
              <% if user_signed_in? %>
                <% if current_user.has_twitter? %>
                  <li><%= link_to "Post Tweet", user_signed_in? ? tweet_user_path(current_user) : "#"  %></li>
                <% end %>
              <% end %>
            </ul>
          </div><!--/.well -->
	<%  end %>
        </div><!--/span-->
        <div class="span9">
          <%- if flash[:notice] %>
            <div class="alert alert-info">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <%= flash[:notice].html_safe %>
            </div>
          <%- end %>
	 <%- if flash[:alert] %>
            <div class="alert alert-info">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <%= flash[:alert].html_safe %>
            </div>
          <%- end %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; <a href="https://www.odesk.com/users/~016b5e45d4e06b6451" target="_blank">Miah Raihan Mahud Arman</a></p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>